#!/usr/bin/expect

set colors(FAIL)  "\033\[1;31m"
set colors(NORM)  "\033\[0;39m"
set colors(PASS)  "\033\[1;32m"

        ;#COLORING FUNCTIONS

proc Print_Pass {statement} {
     global colors
     puts "$statement: \033\[40G$colors(PASS)\[PASS]$colors(NORM)"
}

proc Print_Fail {statement} {
     global colors
     puts "$statement: \033\[40G$colors(FAIL)\[FAIL]$colors(NORM)"
}


log_user 0
##FUNCTION TO LOGIN INTO ROUTER##
proc login {ip} {

##STARTS TELNET PROCESS## 
spawn telnet $ip
puts [Print_Pass "TELNET INTO THE ROUTER $ip"]

expect "Password:" {send "nnt\r"}

expect ">" {send "enable\r"}

expect "Password:" {send "nnt\r"}
expect "#" {send "terminal length 0\r"}
puts [Print_Pass "EXTRACTING RUNNING CONFIGURATION"]

expect "#" {send "show running-config\r"}
expect "#" {send "\r"}

##EXTRACTING THE OUTPUT OF PREVIOUS SEND##
set a $expect_out(buffer)
#puts $a

##TO GENERATE RANDOM NUMBER##
set rand_no [expr int(rand()*100)]
set file1 "config_$rand_no.cfg"
set file2 "inter_$rand_no.txt"

##OPENING THE FILE##
set fp [open "file1" w]
puts $fp "$a"

close $fp 

##SED TO REMOVE THE CONTROL CHARACTERS FROM THE FILE##
exec /bin/sed {s/[[:cntrl:]]//g} file1 >> $file1
puts [Print_Pass "EXTRACTING INTERFACE INFORMATION"]
expect "#" {send "show ip interface brief\r"}
expect "#"

set b $expect_out(buffer)
#puts $b

set fp [open "file2" w]
puts $fp "$b"
close $fp

exec /bin/sed {s/[[:cntrl:]]//g}  file2 >> $file2

##REMOVING THE FILE##
exec rm -rf file1
exec rm -rf file2

}

##FUNCTION CALLING##
login 192.168.1.56
login 192.168.1.57
login 192.168.1.58
